-- Runs ONCE on first PostgreSQL container initialization
-- (docker-entrypoint-initdb.d), in the context of database ${APP_DB}
-- (default `app`) as user ${POSTGRES_USER} (default `bigdata`).
--
-- The `app` database is created automatically by the POSTGRES_DB environment
-- variable; this stack needs no other database, so this script is a no-op
-- placeholder kept for the bind-mount contract in compose.yaml.
